### ISSUE TITLE
Does not respect samesite cookie setting

### ISSUE THREAD

**Issue by larsrinn** [jazzband/django-user-sessions#112]
## Expected Behavior
In the settings, I set:

```python
SESSION_COOKIE_SAMESITE = "Stict"
```
this is respected by the Django session framework and I'd expect `django-user-sessions` to do so, too.

## Current Behavior
The picture should be sufficiently clear:
![grafik](https://user-images.githubusercontent.com/22575361/77157167-1dc5c280-6aa1-11ea-9373-94e49267a4f0.png)

For web deployments, I also have set

```python
SESSION_COOKIE_SECURE = True
```

I presume this is not respected either, but can't confirm this at the moment because this setting is turned off for local development and testing, as we don't have ssl enabled there.

## Steps to Reproduce (for bugs)
1. Set the setting `SESSION_COOKIE_SAMESITE = "Strict"` (or any other value)
1. Login
1. Confirm in the web storage explorer of your devtools that this setting is ignored

## Your Environment

* Browser and version: Firefox 74.0
* Python version: 3.8.1
* Django version: 3.0.4
* django-otp version: Not installed
* django-user-sessions version: 1.7.1
* Link to your project: Irrelevant

**Comment by Bouke** [comment]
Thank you for your contribution!
