### ISSUE TITLE
Security issue with default URL suggestion

### ISSUE THREAD

**Issue by benwhalley** [jazzband/django-user-sessions#128]
The current install instructions suggest that people include `path("sessions/", include("user_sessions.urls", "user_sessions")),` in their urls.py

However without additional work this creates pages which display all active sessions to any users. I think this should be mentioned, and these urls added to the instructions as a separate optional step. These views/urls aren't needed for the operation of the package, and they probably shouldn't be left open as a default.

**Comment by blag** [comment]
Doesn't [this line](https://github.com/jazzband/django-user-sessions/blob/322c88bb7c0d1066517c74dea26499f64cd295bf/user_sessions/views.py#L15) in `views.py` restrict sessions to only those for the current, logged-in user?

**Comment by WhyNotHugo** [comment]
@blag I believe you are correct.

@benwhalley Can you be more specific as to which view you're mentioning here?
