### ISSUE TITLE
Possibility of a new Release

### ISSUE THREAD

**Issue by davidhalter** [jazzband/django-user-sessions#137]
Thanks a lot for `django-user-sessions`. It has been working great for us.

I wanted to ask if it was possible to create a new release? It has been a while and a few patches have landed.

The main reason why I would prefer a new release is https://github.com/jazzband/django-user-sessions/pull/114, which made samesite cookie configuration possible. The current release defaults to `None`, which is not the Django default. This is probably my main gripe with it: You would expect the Django default, which is not the case.

Again thanks for caring about this project for such a long time!

**Comment by Bouke** [comment]
Please refer to #123 to help improve this situation!

**Comment by WhyNotHugo** [comment]
I'd like to tag a new 2.0 release if there are no objections.

Jumping to 2.0 since there's breaking changes (mostly, dropping older Python version).

Any comments?

**Comment by davidhalter** [comment]
I think this is fine. If you have the time, it would be nice if the breaking changes were documented. But I would be fine with a new release in whatever version :).

**Comment by viktorix** [comment]
+1

**Comment by claudep** [comment]
A release would be nice to avoid such "hacks": https://github.com/jazzband/django-two-factor-auth/pull/566

Is there anything preventing the release?

**Comment by WhyNotHugo** [comment]
Will tag a release after merging https://github.com/jazzband/django-user-sessions/pull/147

**Comment by WhyNotHugo** [comment]
> Is there anything preventing the release?

`master` doesn't work with Python 3.6. That Python is EOL, so we should drop it too.

**Comment by WhyNotHugo** [comment]
Currently needing approval: https://github.com/jazzband/django-user-sessions/pull/149

**Comment by davidhalter** [comment]
My review doesn't count. Would I need to become a member of jazzband for it to count?

**Comment by WhyNotHugo** [comment]
@davidhalter Yes. You're welcome to join.

**Comment by WhyNotHugo** [comment]
Release tagged: https://github.com/jazzband/django-user-sessions/releases/tag/2.0.0

There's a [wheel](https://jazzband.co/projects/django-user-sessions/upload/873/download) and [source tarball](https://jazzband.co/projects/django-user-sessions/upload/874/download) ready.

I'll wait until the end of the day before pushing this to PyPI. If anyone wants to early test the above artefacts, feedback is welcome.

**Comment by WhyNotHugo** [comment]
Oh, I'm only a member so can't release new versions, @ricco386 can you chime in?

Via https://jazzband.co/projects/django-user-sessions

**Comment by claudep** [comment]
@jezdez, maybe you can add @WhyNotHugo as project lead here?

**Comment by WhyNotHugo** [comment]
https://pypi.org/project/django-user-sessions/2.0.0/

**Comment by claudep** [comment]
:rocket:
