### ISSUE TITLE
fails to build with django 4

### ISSUE THREAD

**Issue by thierryba** [jazzband/django-user-sessions#145]
## Expected Behavior
it works

## Current Behavior
error message is 
  File ".../python/lib/python3.9/site-packages/user_sessions/models.py", line 3, in <module>
    from django.utils.translation import ugettext_lazy as _
ImportError: cannot import name 'ugettext_lazy' from 'django.utils.translation' 

## Possible Solution
import gettext_lazy

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Browser and version:
* Python version:
* Django version:
* django-otp version:
* django-user-sessions version:
* Link to your project:

**Comment by areski** [comment]
The current version of `django-user-sessions` does not support Django4. 
Although all compatibility issues has been fixed already, eg https://github.com/jazzband/django-user-sessions/commit/1eaaa69d38a1c61fa00a23f8017e7f445ddb882c
You still have to wait for a new release of `django-user-sessions`  to be published [ref: https://github.com/jazzband/django-user-sessions/issues/137]

An alternative would be to install it from Git directly.

**Comment by WhyNotHugo** [comment]
Closing since this is fixed already. Please follow https://github.com/jazzband/django-user-sessions/issues/137 for a new release.
