### ISSUE TITLE
Slow UPDATE queries?

### ISSUE THREAD

**Issue by gijsriet** [jazzband/django-user-sessions#153]
I just noticed that our database logs are filling up with slow query logs from user_sessions.
example:
`:LOG: duration: 1098.946 ms statement: UPDATE "user_sessions_session" SET "session_data" = '.eJxdjslqwzAURf9Fa2M***************************eXZiauZs-J1actew3Sv_Stsljy5vrSQ73ifjs63jOfvw9vLc_gGsVNfjPZFEQE44W8WNnWYMEWYZhCcVuDMIGtDOgryBqC1gdNJLHpXTMkYQB5T8e9oemobrgdVuqytpbylvS-8PfY6glDMOvBbohSEJPoBEwVFTNMj-3dptD-wEA8vFH661UeuVnaaBfeRyTdtl2UNJ-UDLn-gWqBwbPomvbzk-aEo:1oyB3t:Q4zGsSP3r68TnpkyVBCuFJ0cZp8r2Qr6yrFsL3uc5bw', "expire_date" = '2022-11-24T13:10:37.980618+00:00'::timestamptz, "user_id" = ***, "user_agent" = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Safari/605.1.15', "last_activity" = '2022-11-24T12:10:37.980873+00:00'::timestamptz, "ip" = '****************'::inet WHERE "user_sessions_session"."session_key" = 's8daifq5a0wlw55w2ai41DASJSashdba'`

Is anyone else experiencing similar behaviour?

**Comment by WhyNotHugo** [comment]
What database is this? The `session_key` is indexed, do you maybe have a lot of stale sessions (or simply, a huge amount of session?).

Have you tried [clearing the store](https://docs.djangoproject.com/en/4.1/topics/http/sessions/#clearing-the-session-store)?

**Comment by gijsriet** [comment]
Oh wow, I was not aware of this at all. Thanks! 🙌
