### ISSUE TITLE
update readme links

### ISSUE THREAD

**Issue by Arhell** [jazzband/django-user-sessions#156]
http=>https

**Comment by mbeijen** [comment]
Hi Arhell, thanks for noticing this issue. There is currently a pending PR (https://github.com/jazzband/django-user-sessions/pull/151) which already addresses fixing the links in the README by either upgrading the links to HTTPS or pointing to the correct new location altogether: 


https://github.com/jazzband/django-user-sessions/pull/151/commits/a94785a7aa1cb5bca4d1057947fd078640cd6f7d
